spring:
  application:
    name: comment-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: springboot
    password: springboot
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
