spring:
  application:
    name: post-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: springboot
    password: springboot
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    feign=DEBUG: